### PR TITLE
Fix Kafka Channel dispatcher ownerRef

### LINKED ISSUE #1188: kafka-ch-dispatcher has no ownerref
Describe the bug
kafka-ch-dispatcher gets created as needed but without a ownerref, this causes problems on uninstall of eventing as the kafka-ch-dispatcher deployment never gets cleaned up and is left around as an orphan crash loop forever.

Expected behavior
kafka-ch-dispatcher to get cleaned up on uninstall of knative Kafka channel controller.

To Reproduce
Install knative Kafka channel controller
Create a kafka channel
Delete a Kafka channel
Uninstall knative Kafka channel controller

Knative release version
0.14.1

Related issue
https://github.com/knative/eventing/issues/3035

### PR DESCRIPTION
**Pull request by aliok**
Fixes #1188

## Proposed Changes

- Create the dispatcher deployment and service in advance
- Deployment has 0 replicas initially and will be scaled up when the first KafkaChannel is created
- Existing reconcilation logic is kept as it is harmless
- Also tested with namespaced channels

**Release Note**

```release-note
🐛 Fix bug
Cluster scoped KafkaChannel dispatcher is now created with 0 replicas in advance and will be scaled up with the creation of the first KafkaChannel. No manual operation is needed when upgrading.
```

**Docs**

### CODE REVIEW

**Comment by aliok** [comment]
cc @lionelvillard

**Comment by slinkydeveloper** [comment]
This approach makes sense to me :+1: 

/lgtm
/approve
/hold waiting for @lionelvillard approval

File: kafka/channel/pkg/reconciler/controller/kafkachannel.go [hunk 1]
```diff
@@ -294,17 +294,28 @@ func (r *Reconciler) reconcileDispatcher(ctx context.Context, scope string, disp
...
-		if err == nil {
-			controller.GetEventRecorder(ctx).Event(kc, corev1.EventTypeNormal, dispatcherDeploymentUpdated, "Dispatcher deployment updated")
-			kc.Status.PropagateDispatcherStatus(&d.Status)
-			return d, nil
-		} else {
-			kc.Status.MarkServiceFailed("DispatcherDeploymentUpdateFailed", "Failed to update the dispatcher deployment: %v", err)
+	} else {
+		needsUpdate := false
+
+		if !reflect.DeepEqual(expected.Spec.Template.Spec.Containers[0].Image, d.Spec.Template.Spec.Containers[0].Image) {
```
Comment (lionelvillard) [inline kafka/channel/pkg/reconciler/controller/kafkachannel.go:300]: I think it would be safer to look for the container by name, just in case the operator decide to add additional  containers to the dispatcher deployment.

File: kafka/channel/pkg/reconciler/controller/kafkachannel.go [hunk 2]
```diff
@@ -294,17 +294,28 @@ func (r *Reconciler) reconcileDispatcher(ctx context.Context, scope string, disp
...
+			logging.FromContext(ctx).Infof("Deployment image is not what we expect it to be, updating Deployment Got: %q Expect: %q", expected.Spec.Template.Spec.Containers[0].Image, d.Spec.Template.Spec.Containers[0].Image)
+			needsUpdate = true
+		} else if !reflect.DeepEqual(expected.Spec.Replicas, d.Spec.Replicas) {
```
Comment (lionelvillard) [inline kafka/channel/pkg/reconciler/controller/kafkachannel.go:303]: this prevents dispatchers to scale to more than 1 replicas. The logic is if replicas is 0 then scale to 1, otherwise no update.

Comment (aliok) [reply kafka/channel/pkg/reconciler/controller/kafkachannel.go:303]: Let me improve

File: kafka/channel/pkg/reconciler/controller/kafkachannel.go (hunk 1 above)
Comment (aliok) [reply kafka/channel/pkg/reconciler/controller/kafkachannel.go:300]: Oh, good point

Comment (aliok) [reply kafka/channel/pkg/reconciler/controller/kafkachannel.go]: Fixed

File: kafka/channel/pkg/reconciler/controller/kafkachannel.go (hunk 2 above)
Comment (aliok) [reply kafka/channel/pkg/reconciler/controller/kafkachannel.go]: Fixed

File: kafka/channel/pkg/dispatcher/dispatcher.go [hunk 3]
```diff
@@ -90,7 +90,7 @@ func NewDispatcher(ctx context.Context, args *KafkaDispatcherArgs) (*KafkaDispat
 
 	producer, err := sarama.NewAsyncProducer(args.Brokers, conf)
 	if err != nil {
-		return nil, fmt.Errorf("unable to create kafka producer: %v", err)
+		return nil, fmt.Errorf("unable to create kafka producer for brokers %v : %v", args.Brokers, err)
```
Comment (aliok) [inline kafka/channel/pkg/dispatcher/dispatcher.go:93]: Minor irrelevant improvement that I noticed while testing against namespace scoped channels. Wanted to see what broker is used. Relevant: https://github.com/knative/eventing-contrib/issues/1189

File: kafka/channel/pkg/utils/util.go [hunk 4]
```diff
@@ -89,3 +91,13 @@ func TopicName(separator, namespace, name string) string {
 	topic := []string{knativeKafkaTopicPrefix, namespace, name}
 	return strings.Join(topic, separator)
 }
+
+func FindContainer(d *appsv1.Deployment, containerName string) *corev1.Container {
```
Comment (aliok) [inline kafka/channel/pkg/utils/util.go:95]: I couldn't find a function like this in the codebase. Any pointers?

File: kafka/channel/pkg/dispatcher/dispatcher.go (hunk 3 above)
Comment (matzew) [reply kafka/channel/pkg/dispatcher/dispatcher.go:93]: Kafka broker?  

Broker is an overloaded term

File: kafka/channel/config/500-kafka-ch-dispatcher.yaml [hunk 5]
```diff
@@ -0,0 +1,83 @@
+# Copyright 2018 The Knative Authors
```
Comment (matzew) [inline kafka/channel/config/500-kafka-ch-dispatcher.yaml:1]: 2020 ?

Comment (matzew) [inline kafka/channel/config/500-kafka-ch-dispatcher.yaml:1]: the file could be named `500-dispatcher.yaml` to match the others?

also, we had that name for this file before... see:
https://github.com/knative/eventing-contrib/blob/release-0.12/kafka/channel/config/500-dispatcher.yaml

related PR from FEB: #922

File: kafka/channel/pkg/dispatcher/dispatcher.go (hunk 3 above)
Comment (aliok) [reply kafka/channel/pkg/dispatcher/dispatcher.go:93]: Ok, let me change to "Kafka bootstrap servers"

File: kafka/channel/config/500-kafka-ch-dispatcher.yaml (hunk 5 above)
Comment (aliok) [reply kafka/channel/config/500-kafka-ch-dispatcher.yaml:1]: LOL how did you even catch that?

Comment (aliok) [reply kafka/channel/config/500-kafka-ch-dispatcher.yaml:1]: +1

Comment (aliok) [reply kafka/channel/config/500-kafka-ch-dispatcher.yaml]: Done

Comment (aliok) [reply kafka/channel/config/500-kafka-ch-dispatcher.yaml]: Done

File: kafka/channel/pkg/dispatcher/dispatcher.go (hunk 3 above)
Comment (aliok) [reply kafka/channel/pkg/dispatcher/dispatcher.go]: Done

File: kafka/channel/pkg/reconciler/controller/kafkachannel.go [hunk 6]
```diff
@@ -294,17 +295,51 @@ func (r *Reconciler) reconcileDispatcher(ctx context.Context, scope string, disp
...
+			logging.FromContext(ctx).Errorw("Container %s does not exist in existing dispatcher deployment. Updating the deployment", resources.DispatcherContainerName)
+			d, err := r.KubeClientSet.AppsV1().Deployments(dispatcherNamespace).Update(expected)
+			if err == nil {
+				controller.GetEventRecorder(ctx).Event(kc, corev1.EventTypeNormal, dispatcherDeploymentUpdated, "Dispatcher deployment updated")
+				kc.Status.PropagateDispatcherStatus(&d.Status)
+				return d, nil
+			} else {
+				kc.Status.MarkServiceFailed("DispatcherDeploymentUpdateFailed", "Failed to update the dispatcher deployment: %v", err)
+			}
+			return d, newDeploymentWarn(err)
```
Comment (matzew) [inline kafka/channel/pkg/reconciler/controller/kafkachannel.go:310]: Isn't that like: https://github.com/knative/eventing-contrib/pull/1536/files#diff-c0164358c6e61a5abb38a4914a1dc150R332-R341

File: kafka/channel/pkg/utils/util.go (hunk 4 above)
Comment (matzew) [reply kafka/channel/pkg/utils/util.go:95]: hrm...

Comment (lionelvillard) [reply kafka/channel/pkg/utils/util.go:95]: same. I ended-up implemented it. https://github.com/knative/eventing/blob/master/pkg/reconciler/pingsource/pingsource.go#L198

File: kafka/channel/config/500-kafka-ch-dispatcher.yaml (hunk 5 above)
Comment (matzew) [reply kafka/channel/config/500-kafka-ch-dispatcher.yaml]: that was my bot :-P @aliok

**Comment by n3wscott** [comment]
/lgtm

This sets us up for different kinds of deployments as the dispatcher as well in the future with a bit more work.

File: kafka/channel/pkg/reconciler/controller/kafkachannel.go (hunk 6 above)
Comment (aliok) [reply kafka/channel/pkg/reconciler/controller/kafkachannel.go:310]: Pushed a new commit and made it easier to understand now.
Looks more similar to old code: https://github.com/knative/eventing-contrib/blob/master/kafka/channel/pkg/reconciler/controller/kafkachannel.go#L307

**Comment by aliok** [comment]
Code changes to address comments are not unit tested yet. Let me do them first.

File: kafka/channel/pkg/utils/util.go (hunk 4 above)
Comment (aliok) [reply kafka/channel/pkg/utils/util.go:95]: /hold
Ok, looks like I need to write some unit tests...

Comment (aliok) [reply kafka/channel/pkg/utils/util.go:95]: /unhold

Done with unit tests.
Next time I need this, I will refactor it into a function in knative/pkg

**Comment by aliok** [comment]
@matzew @lionelvillard 
This is all green now, ready for another look

File: kafka/channel/pkg/reconciler/controller/kafkachannel.go [hunk 7]
```diff
@@ -294,17 +296,51 @@ func (r *Reconciler) reconcileDispatcher(ctx context.Context, scope string, disp
...
+		needsUpdate := false
+
+		if existing.Image != expectedContainer.Image {
+			logging.FromContext(ctx).Infof("Dispatcher deployment image is not what we expect it to be, updating Deployment Got: %q Expect: %q", expected.Spec.Template.Spec.Containers[0].Image, d.Spec.Template.Spec.Containers[0].Image)
+			existing.Image = expectedContainer.Image
+			needsUpdate = true
+		}
+
+		if *d.Spec.Replicas == 0 {
+			logging.FromContext(ctx).Infof("Dispatcher deployment has 0 replicas. Scaling up deployment to 1 replicas")
```
Comment (lionelvillard) [inline kafka/channel/pkg/reconciler/controller/kafkachannel.go:328]: nit: replicas -> replica, both instances.

**Review by matzew — APPROVED** [review]
/lgtm
/approve
