### PR TITLE
[0.17] Fix KafkaSource conversion

### LINKED ISSUE #1649: [0.17] Constant reconciliation for KafkaSource when it is created as `v1beta1`
**Describe the bug**
Constant reconciliation for KafkaSource when it is created as `v1beta1`

```
 {"level":"info","ts":"2020-10-27T12:13:04.174Z","logger":"kafka-controller.knative.dev-eventing-contrib-kafka-source-pkg-reconciler-source.Reconciler","caller":"controller/controller.go:520","msg":"Reconcile succeeded. Time taken: 22.018803ms","knative.dev/traceid":"f438352f-8da9-40b4-9e32-524d9d5f2c40","knative.dev/key":"default/kafka-source"}
```

 **Expected behavior**
No constant reconciliation

 **To Reproduce**
Create Kafka topic
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 100
  replicas: 1
```

Create `ksvc`
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "5"
    spec:
      containers:
        - image: quay.io/openshift-knative/knative-eventing-sources-event-display
```
Create KafkaSource
```
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  bootstrapServers:
   - my-cluster-kafka-bootstrap.kafka:9092
  topics:
   - my-topic
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
```

 **Knative release version**
Tried with eventing v0.17.7 and eventing-contrib v0.17.4

 **Additional context**

Debugging session with Ville: https://knative.slack.com/archives/CQBKVH4QY/p1603801829059700

### PR DESCRIPTION
**Pull request by aliok**
Fixes #1649

## Proposed Changes

- Fix KafkaSource conversion

That conversion had 2 problems:
- It was wrong that it was converting the source status into the **source** status again and this caused unnecessary updates in the status
- It was truncating the conditions other than `Ready`

Conversion tests had roundtrip test cases but they didn't fail. Now with 2 conditions the previous code makes the tests fail.

**Release Note**

```release-note
- 🐛 Fix bug
Fix KafkaSource conversion which resulted in reconcilation churn
```

### CODE REVIEW

File: kafka/source/pkg/apis/sources/v1alpha1/kafka_conversion.go [hunk 1]
```diff
@@ -44,8 +44,7 @@ func (source *KafkaSource) ConvertTo(ctx context.Context, obj apis.Convertible)
 			Topics:        source.Spec.Topics,
 			ConsumerGroup: source.Spec.ConsumerGroup,
 		}
-		sink.Status.Status = source.Status.Status
-		source.Status.Status.ConvertTo(ctx, &sink.Status.Status)
+		source.Status.Status.DeepCopyInto(&sink.Status.Status)
```
Comment (aliok) [inline kafka/source/pkg/apis/sources/v1alpha1/kafka_conversion.go:47]: Instead of `.ConvertTo`, I used `DeepCopyInto` since `ConvertTo` was removing the conditions other than `Ready`.
I see status is handled like that in other sources, for example in here: https://github.com/knative/eventing/blob/master/pkg/apis/sources/v1alpha2/apiserver_conversion.go#L85

File: kafka/source/pkg/apis/sources/v1alpha1/kafka_conversion_test.go [hunk 2]
```diff
@@ -163,6 +163,9 @@ func TestKafkaSourceConversionRoundTripV1alpha1(t *testing.T) {
 						Conditions: duckv1.Conditions{{
 							Type:   "Ready",
 							Status: "True",
+						}, {
+							Type:   "SinkProvided",
+							Status: "True",
```
Comment (aliok) [inline kafka/source/pkg/apis/sources/v1alpha1/kafka_conversion_test.go:168]: When I added this condition, the test started to fail with the previous conversion code.

**Comment by aliok** [comment]
this is to be done in 0.18 in this repo and also in master in knative-sandbox/eventing-kafka

**Comment by vaikas** [comment]
/lgtm
/approve

Should probably cherrypick to .17, .18, etc.?

**Comment by aliok** [comment]
> Should probably cherrypick to .17, .18, etc.?

this is against 0.17 :) prefer having against master in knative-sandbox/eventing-kafka first?

feel free to unhold if this PR is just OK

**Comment by aliok** [comment]
cc @vaikas

**Comment by vaikas** [comment]
for the head I'd like us to use fuzzers because they catch so many things :)
/unhold

**Comment by vaikas** [comment]
Of course it's against .17 :)
should cp for .18, yes?

**Comment by aliok** [comment]
> should cp for .18, yes?

yep

**Comment by aliok** [comment]
This is already fixed on 0.18: https://github.com/knative/eventing-contrib/pull/1645
and on master: https://github.com/knative-sandbox/eventing-kafka/pull/128

No cherry pick needed
