### PR TITLE
Fixing missing error handling in kafka consumer group handler

### LINKED ISSUE #851: kafka consumer_factory consumerGroup.Consume connection errors are ignored
https://github.com/knative/eventing-contrib/blob/86bac88600f79123e3e29babc33a44007c6ff419/kafka/common/pkg/kafka/consumer_factory.go#L80-L81

consumerGroup.Consume errors are ignored.

While the comment "// If any error, they are reported in error channel, so we can skip this message" suggests it is not needed, it is not exactly true, as it may return connection errors even before the error channel is setup. 

We should assume that if consumerGroup.Consume returns an error, it didn't start the consumer group properly (and perhaps retry?)

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

Fixes #851

### CODE REVIEW

File: kafka/common/pkg/kafka/consumer_factory.go [hunk 1]
```diff
@@ -77,8 +77,10 @@ func (c kafkaConsumerGroupFactoryImpl) StartConsumerGroup(groupID string, topics
 	consumerHandler := NewConsumerHandler(logger, handler)
 
 	go func() {
-		// If any error, they are reported in error channel, so we can skip this message
-		_ = consumerGroup.Consume(context.TODO(), topics, &consumerHandler)
+		err2 := consumerGroup.Consume(context.TODO(), topics, &consumerHandler)
```
Comment (matzew) [inline kafka/common/pkg/kafka/consumer_factory.go]: not fancy w/ `err2` - but we have done that before
