### PR TITLE
[0.17] Fix KafkaBinding conversion

### LINKED ISSUE #1648: [0.17] KafkaBinding conversion problems
**Describe the bug**
Getting this on 0.17 branch:
```
"level":"error","ts":"2020-10-27T07:37:16.393Z","logger":"kafka-controller.ConversionWebhook","caller":"controller/controller.go:526","msg":"Reconcile error","error":"custom resource \"kafkabindings.bindings.knative.dev\" isn't configured for webhook conversion", 
```

 **Expected behavior**
No error

 **To Reproduce**
Create a KafkaSource with a `ksvc` sink

 **Knative release version**
0.17
Tried with eventing v0.17.7 and eventing-contrib v0.17.4

 **Additional context**
Add any other context about the problem here such as proposed priority

### PR DESCRIPTION
**Pull request by aliok**
Fixes #1648

## Proposed Changes

- Add missing conversion webhook config for KafkaBinding
- Fix the conversion problems noticed during https://github.com/knative/eventing-contrib/pull/1650 (#1650 is for KafkaSource but I saw that same problems also exist in KafkaBinding conversion)

**Release Note**

```release-note
- 🐛 Fix bug
Fix KafkaBinding conversion
```

**Docs**

### CODE REVIEW

File: kafka/source/pkg/apis/bindings/v1alpha1/kafka_conversion_test.go [hunk 1]
```diff
@@ -147,6 +147,9 @@ func TestKafkaBindingConversionRoundTripV1alpha1(t *testing.T) {
 					Conditions: duckv1.Conditions{{
 						Type:   "Ready",
 						Status: "True",
+					}, {
+						Type:   "DoesNotReallyExistButHereItIsForTestingStatusCopy",
+						Status: "False",
```
Comment (aliok) [inline kafka/source/pkg/apis/bindings/v1alpha1/kafka_conversion_test.go:152]: The old conversion test would've failed if we had a status with a condition other than `Ready` in it. I just added this imaginary condition to make sure we're not truncating the status conditions when doing the conversion.

**Comment by aliok** [comment]
/assign @vaikas 
Pretty much the same thing as https://github.com/knative/eventing-contrib/pull/1650 but also has a small fix for #1648

File: kafka/source/config/300-kafkabinding.yaml [hunk 2]
```diff
@@ -22,6 +22,15 @@ metadata:
   name: kafkabindings.bindings.knative.dev
 spec:
   group: bindings.knative.dev
+  preserveUnknownFields: false
```
Comment (matzew) [inline kafka/source/config/300-kafkabinding.yaml:25]: oh... look, I did forget that part in here: https://github.com/knative/eventing-contrib/commit/84c21fbb9cc0d33fe5ae24e6e2593b64cc11f0e6   - sorry, @aliok

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by aliok** [comment]
Cherry pick on 0.18: https://github.com/knative/eventing-contrib/pull/1652
