### PR TITLE
[Backport 0.16] Fix KafkaChannel conversion (#1398)

### LINKED ISSUE #1539: Kafka Channel wont delete
**Describe the bug**
I can't delete the kafka channel due to the following error:

admission webhook "validation.webhook.kafka.messaging.knative.dev" denied the request: decoding request failed: cannot decode incoming old object: json: unknown field "subscribable"

 **Expected behavior**
I can delete the channel

 **To Reproduce**
deploy a channel and a subscription to that channel
delete subscription and channel
watch the channel get stuck

 **Knative release version**

v0.16

### PR DESCRIPTION
**Pull request by aliok**
(cherry picked from commit e4de8d36412c54da4722cc35eb2a748424c8edf5)

Fixes #1539

## Proposed Changes

- Backport https://github.com/knative/eventing-contrib/pull/1398 as it affects 0.16 too. See https://github.com/knative/eventing-contrib/issues/1539

**Release Note**

```release-note
- 🐛 Fix bug
Fix KafkaChannel conversion
```

**Docs**

Verification:
- Try the instructions at https://github.com/knative/eventing-contrib/issues/1539

### CODE REVIEW

**Comment by aliok** [comment]
/hold

This will need a new patch release. Please unhold if you think it is ok to make a new release.

cc @vaikas @slinkydeveloper

**Comment by slinkydeveloper** [comment]
I'm ok with a new release, this seems like an important issue

/lgtm

File: kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_conversion.go [hunk 1]
```diff
@@ -65,14 +65,21 @@ func (source *KafkaChannel) ConvertTo(ctx context.Context, obj apis.Convertible)
...
+				if ss.Delivery != nil {
+					if err := ss.Delivery.ConvertTo(ctx, delivery); err != nil {
+						return err
+					}
+				}
+
+				var subscriberURI *apis.URL
+				if ss.SubscriberURI != nil {
+					subscriberURI = ss.SubscriberURI.DeepCopy()
 				}
```
Comment (pierDipi) [inline kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_conversion.go:77]: There is no need to check if `SubscriberURI` is nil since `DeepCopy` handles the nil case.

**Review by pierDipi — APPROVED** [review]
+1 for a release.

If you want to address the comment.

/lgtm

File: kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_conversion.go (hunk 1 above)
Comment (aliok) [reply kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_conversion.go:77]: Nice catch!

But, if that's ok, let's leave the cherry pick as is?

Comment (pierDipi) [reply kafka/channel/pkg/apis/messaging/v1alpha1/kafka_channel_conversion.go:77]: I'm ok with that.

**Comment by vaikas** [comment]
/hold cancel
Thanks@
